/// <reference types="@cloudflare/workers-types" />
// @ts-expect-error — generated by `opennextjs-cloudflare build`, absent until then.
import { default as handler } from "./.open-next/worker.js";

/**
 * Custom Worker entrypoint.
 *
 * WHY THIS FILE EXISTS: the worker OpenNext generates exports only a `fetch`
 * handler. Cloudflare Cron Triggers invoke `scheduled()`. Without this wrapper
 * the cron in wrangler.jsonc would fire every 5 minutes and do nothing —
 * expired seat holds would sit there until Stripe's webhook happened to clear
 * them, and any hold whose webhook got lost would block a seat forever.
 *
 * So: re-export OpenNext's fetch handler untouched, and add a scheduled
 * handler that calls our own cron route in-process.
 */
export default {
  fetch: handler.fetch,

  async scheduled(
    _event: ScheduledController,
    env: { CRON_SECRET?: string },
    ctx: ExecutionContext
  ) {
    const run = async () => {
      const secret = env.CRON_SECRET;
      if (!secret) {
        console.error("[cron] CRON_SECRET is not set — skipping hold sweep");
        return;
      }

      // The hostname is arbitrary; this request never leaves the Worker.
      const req = new Request("https://cron.internal/api/cron/expire-holds", {
        headers: { authorization: `Bearer ${secret}` },
      });

      try {
        const res = await handler.fetch(req, env as never, ctx);
        const body = await res.text();
        if (!res.ok) {
          console.error(`[cron] sweep failed ${res.status}: ${body}`);
        } else {
          const { released } = JSON.parse(body) as { released: number };
          if (released > 0) console.log(`[cron] released ${released} hold(s)`);
        }
      } catch (err) {
        // Cloudflare does not retry a failed scheduled run. That's fine — the
        // next one is five minutes away and does identical work.
        console.error("[cron] sweep threw", err);
      }
    };

    ctx.waitUntil(run());
  },
};
